### ISSUE TITLE
[Github Action] CI failing due to module "pandas" not imported

### ISSUE THREAD

**Issue by zztin** [zztin/ctimer#25]
## Description
**Describe the bug**
Pandas dependency is updated in requirement_dev.txt but while running action, it fails with error: 

____________________ ERROR collecting tests/test_ctimer.py _____________________
ImportError while importing test module '/home/runner/work/ctimer/ctimer/tests/test_ctimer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_ctimer.py:8: in <module>
    from concentratetimer import concentratetimer
concentratetimer/concentratetimer.py:7: in <module>
    import concentratetimer.ctimer_db as db
concentratetimer/ctimer_db.py:8: in <module>
    import pandas as pd
E   ModuleNotFoundError: No module named 'pandas'

* ctimer version:  since https://github.com/zztin/ctimer/runs/967596325?check_suite_focus=true
* Python version: 3.7.8
* Operating System:

## Steps to Reproduce
Check this page: 
https://github.com/zztin/ctimer/runs/967596325?check_suite_focus=true

**Comment by tai271828** [comment]
If I understand correctly, we have fixed this by adding pip manipulation in workflow configuration?
