### ISSUE TITLE
[Feature Request] Customize ctimer.db location (in case of sharedrive)

### ISSUE THREAD

**Issue by zztin** [zztin/ctimer#26]
## Is your feature request related to a problem?
Now the ctimer is located within the package itself and cannot be share between different computers. If we allows users to store the files by their choice, they can save it on a cloud folder which automatically updates. In this case, the database can be shared amount different devices of the same users (or even shared between team members). 

## Describe the solution you'd like
Customize ctimer.db saving path. Next time, the program should find back this parameter.
(The parameter of path route could be save in a txt file as a path in computer's home folder .ctimer or so.)

**Comment by tai271828** [comment]
Per discussion, we may use symbolic links to achieve synchronizing. So what we need to do is only adding one more extra argument to customize the db path.

**Comment by zztin** [comment]
As @tai271828 suggested. This could be done outside of the ctimer codebase. Step to achieve this:

1. go to your share drive location. `cd <drive_location_for_ctimer.db>`
2. `ln -s <original_location_for_ctimer.db> .`

**Comment by zztin** [comment]
The user can now define database path and the path will be access in next login. commit:49a18c496e7861d385b7650d49ef87523ae13aca
