### ISSUE TITLE
[Feature Request] Show precise timestamp in stats

### ISSUE THREAD

**Issue by tai271828** [zztin/ctimer#41]
It will be helpful to make a daily review or journal if we show the time of started clocks.

## Describe the solution you'd like
Show timestamps on the panel by passing an option.

## Describe alternatives you've considered
Show timestamps in terminal.

**Comment by zztin** [comment]
Hi Tai, 
In commit 317e84 we implement a new statistic file recording all the details related to all the clocks you've ever started (start, end time and goals etc) in a html format. It will show when calling:
`ctimer --stats`
